package com.zooper.ws.hellows;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.0
 * 2017-10-10T14:38:07.333+08:00
 * Generated source version: 3.2.0
 * 
 */
@WebService(targetNamespace = "http://hellows.ws.zooper.com/", name = "HelloWS")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloWS {

    @WebMethod
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://hellows.ws.zooper.com/", className = "com.zooper.ws.hellows.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://hellows.ws.zooper.com/", className = "com.zooper.ws.hellows.SayHelloResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String sayHello(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
