package com.zooper.ws.datatype;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.13
 * 2017-10-10T17:56:06.043+08:00
 * Generated source version: 3.1.13
 * 
 */
@WebService(targetNamespace = "http://dataType.ws.zooper.com/", name = "DataTypeWS")
@XmlSeeAlso({ObjectFactory.class})
public interface DataTypeWS {

    @WebMethod
    @RequestWrapper(localName = "getStudentBySex", targetNamespace = "http://dataType.ws.zooper.com/", className = "com.zooper.ws.datatype.GetStudentBySex")
    @ResponseWrapper(localName = "getStudentBySexResponse", targetNamespace = "http://dataType.ws.zooper.com/", className = "com.zooper.ws.datatype.GetStudentBySexResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.zooper.ws.datatype.Student> getStudentBySex(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getAllStudentsMap", targetNamespace = "http://dataType.ws.zooper.com/", className = "com.zooper.ws.datatype.GetAllStudentsMap")
    @ResponseWrapper(localName = "getAllStudentsMapResponse", targetNamespace = "http://dataType.ws.zooper.com/", className = "com.zooper.ws.datatype.GetAllStudentsMapResponse")
    @WebResult(name = "_return", targetNamespace = "")
    public com.zooper.ws.datatype.GetAllStudentsMapResponse.Return getAllStudentsMap();

    @WebMethod
    @RequestWrapper(localName = "getStudentById", targetNamespace = "http://dataType.ws.zooper.com/", className = "com.zooper.ws.datatype.GetStudentById")
    @ResponseWrapper(localName = "getStudentByIdResponse", targetNamespace = "http://dataType.ws.zooper.com/", className = "com.zooper.ws.datatype.GetStudentByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.zooper.ws.datatype.Student getStudentById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebMethod
    @RequestWrapper(localName = "addStudent", targetNamespace = "http://dataType.ws.zooper.com/", className = "com.zooper.ws.datatype.AddStudent")
    @ResponseWrapper(localName = "addStudentResponse", targetNamespace = "http://dataType.ws.zooper.com/", className = "com.zooper.ws.datatype.AddStudentResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean addStudent(
        @WebParam(name = "arg0", targetNamespace = "")
        com.zooper.ws.datatype.Student arg0
    );
}
